### PR TITLE
Closes #004 - Create section footer

### LINKED ISSUE #4: Create section footer in index.html

### PR DESCRIPTION
**Pull request by stasoz**

### CODE REVIEW

**Review by tarasbiletsky24 — CHANGES_REQUESTED** [review]
Add number to the name of commit

**Review by martakondor — CHANGES_REQUESTED** [review]
Add issue number.

**Review by nikita-namely — CHANGES_REQUESTED** [review]
Add issue number.

**Review by koldovsky — DISMISSED** [review]
Please name pull request according to naming convetions

**Review by vov4ik-7 — APPROVED** [review]

**Review by tarasbiletsky24 — APPROVED** [review]

**Review by martakondor — APPROVED** [review]

**Review by nikita-namely — APPROVED** [review]

**Review by bibipkins — APPROVED** [review]

**Pull request merged**
